### ISSUE TITLE
In MIPS TLB, Confusion between virtual and physical addresses

### ISSUE THREAD

**Issue by Azizelmad** [MIPSfpga/schoolMIPS#29]
0
down vote
favorite
I have some C code running in RTL mode, I use CPU I6400 the C code is just a simple code to read and write from some subsystem, for example,

I tried to write in this address :  0x001e400000 (physical address) so when CPU executes this address I got a TLB exception because this address is a mapped area, after many research I fond that I need to translate this address from Virtual address to physical address, I replace this address by 0xffffffffbe400000 (Kseg1), now im able to write some value in this address is done, But when I tried to read from this address(W/R) or another address I got an exception on KSEG2,

Have you an idea why the writing step pass correctly but the reading step generate a exception?

**Comment by zhelnio** [comment]
This is not a schoolMIPS issue
